### ISSUE TITLE
Multi-level lists break

### ISSUE THREAD

**Issue by jean** [dgsuarez/vim-ticard#1]
Plain ticard:

```
...:~/repos/git/ticard(master)$ cat troubleshooting-doc_asdfasdf.md 
<!---
url https://trello.com/c/asdfasdf/1397-troubleshooting-doc
md5 d4c2352...
-->

- Diagnosing failure:
  - 503? 
  - site unreachable? 
  - mail delivery?
  - database corruption?
  - ...
- Appropriate action in each case:
  - restart site
  - reset router
...
```

In vim:

```
...
-   Diagnosing failure:
-   503?
-   site unreachable?
-   mail delivery?
-   database corruption?
-   ...
-   Appropriate action in each case:
-   restart site
-   reset router
...
```
- indentation is lost
- spacing after `-` is changed (from one space to three)

**Comment by dgsuarez** [comment]
Hi, thanks for reporting! 

This issue is due to vim-ticard using pandoc to reformat outgoing markdown. This allows for hard line breaks to work for example. In this case, default pandoc expects 4 space tabs instead of 2 space ones.

You can disable pandoc filtering by doing `let g:ticard_pandoc_disabled = 1` in your .vimrc

However it would be pretty easy to add a `g:ticard_pandoc_tab_stops` in order to parameterize pandoc, I'll look into it when I have a spare moment.

**Comment by dgsuarez** [comment]
I've added the functionality to configure tab stops in pandoc. `let g:ticard_pandoc_tabstop = 2` in .vimrc to use it
